# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d03142be835cb88d5aa0b405fc4f6aab5e4f89efed0e001beb97baa2011fa29e4d90cbdaee946fed97174cafc123d3db9e9793913f5925929030912b6d46cdb

test:
  secret_key_base: e60c6d3076561b06b77899578577c5d23f080ab1328b07c352900e286ec786fb14ee974d04263ff09cdb304fc855765e0184e50f4bcdbcf1e8164a1e282b35e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
